# Generated by Django 4.2 on 2024-08-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="defaultdomain",
        ),
        migrations.RemoveField(
            model_name="user",
            name="defaultprogram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ref_language",
        ),
    ]
